language: c
script:
  - make vars
  - DEBUG=1 make vars
  - CC="time clang" make test/optimized
  - ASAN_OPTIONS=detect_leaks=0 make test/poll
  - ASAN_OPTIONS=detect_leaks=0 make test/ci
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
